schema_version: 1

context:
  version: "1.0.3"
  python_min: "3.11"

package:
  name: specify-cli
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/specify-cli/specify_cli-${{ version }}.tar.gz
  sha256: a3150d3cbf28ecbb6985478513fa1649f673dc588de824d236866656cc207c47

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - specify = specify_cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - typer
    - rich
    - httpx
    - platformdirs
    - readchar
    - truststore >=0.10.4

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - '*'
      imports:
        - specify_cli
      pip_check: true
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - specify --help

about:
  summary: Specify CLI, part of GitHub Spec Kit. A tool to bootstrap your projects for Spec-Driven Development (SDD).
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/specify-cli/
  repository: https://github.com/github/spec-kit

extra:
  recipe-maintainers:
    - xhochy
